### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Zumbalamambo** [xeno14/UnityVR220Shader#2] opened 2019-05-15 07:15 UTC
It just displays a black screen. I used Unity 2018.2

**Comment by xeno14** [comment] 2019-05-15 14:35
@Zumbalamambo
Could you try Assets/Scenes/SampleScene? I'm not using that version but it works for me in Unity 2019.1.2f1

![キャプチャ](https://user-images.githubusercontent.com/1827523/57783930-ffe54e00-7769-11e9-804c-2b9711d94c2b.PNG)

**Comment by Zumbalamambo** [comment] 2019-05-15 14:44
Yes I tried but still the same issue. I have also tried on 2019 version and Im getting the same issue

**Comment by xeno14** [comment] 2019-05-15 14:48
@Zumbalamambo 
Could you send me a screenshot? Do you see Main Camera and Screen (a sphere material) in the scene?

**Comment by Zumbalamambo** [comment] 2019-05-16 06:35
No i dont see the main camera or the sphere. The screen is just entirely black with the latest version of Unity. please try it with the latest version of Unity

**Comment by xeno14** [comment] 2019-05-16 14:23
@Zumbalamambo 
Let me close this issue because I cannot reproduce the issue. Confirmed it works in Unity 2019.1.2f1 on Windows (pls see the screenshot).

![キャプチャ](https://user-images.githubusercontent.com/1827523/57861166-160a1180-7831-11e9-897b-f10ada0728b5.PNG)

One possible reason I just came up with is that the screen is not facing the front (z-axis). Please try right click and drag to rotate the direction and check Camera Preview as well. If it does not work, please scratch a Scene.

**Closed as completed** 2019-05-16 14:23 UTC
